version: '3'

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    env_file: .env
    depends_on:
      - db
      - redis

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'

volumes:
  bundle_cache:
  node_modules:
  postgres:
