default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: '5432'
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: all_the_things_development

test:
  <<: *default
  database: all_the_things_test

production:
  <<: *default
  database: all_the_things_production
  username: all_the_things
  password: <%= ENV["ALL_THE_THINGS_DATABASE_PASSWORD"] %>
